import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";

const geistInter = Inter({
  variable: "--font-geist-inter",
  subsets: ["latin"],
});

const geistManrope = Manrope({
  variable: "--font-geist-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio Suphanat Chanlek",
  description: "Generated by Suphanat Chanlek",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistInter.variable} ${geistManrope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
